version: '3'

services:
  web:
    build: .

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 19922301
      POSTGRES_USER: postgres
      POSTGRES_DB: Event2

    ports:
      - 5433:5432
